server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: localhost8848
  datasource:
    url: jdbc:mysql://localhost:3306/seata_order
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info