server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    # false --> 自己不注册自己
    register-with-eureka: false
    # false --> 注册中心，维护服务实例，不需要检索服务
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#  server:
# 是否开启自我保护机制 建议开启保证高可用
#    enable-self-preservation: false
# 2s之后接收不到心跳就做掉（默认90s）
#    eviction-interval-timer-in-ms: 2000